main: to.minecraft.elitesquad.plugin.MinecraftServerPlugin
version: 1.1.0
name: MinecraftServerPlugin
description: Plugin sorgt dafür, dass nur ein Spieler in einer Welt schlafen muss, damit dort Tag wird.
